name: Build and Push

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build & Push the image to docker.io
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: xenontheinertg/docky
          tags: latest
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build & push to ghcr.io
        run: |
             echo ${{ secrets.GH_TOKEN }} | docker login ghcr.io -u xenontheinertg@outlook.com --password-stdin
             docker build -t ghcr.io/xenontheinertg@outlook.com/arch:latest .
             echo "Build Completed Successfully!"
             docker push ghcr.io/xenontheinertg@outlook.com/arch:latest
